### ISSUE TITLE
Part Number/DeviceType Update

### ISSUE THREAD

**Issue by typecookie** [netbox-community/Device-Type-Library-Import#27] opened 2021-07-02 15:21 UTC
There where several Ubiquiti devises with the device type and part number backwards on the device type library, This has been fixed but running the Import script dose not recognize this. 
![2021-07-02 09_20_39-Ubiquiti by typecookie · Pull Request #422 · netbox-community_devicetype-library](https://user-images.githubusercontent.com/46032657/124296135-dd177e80-db16-11eb-9ae1-5abfb75100ef.png)

**Comment by ndom91** [comment] 2021-07-02 15:26
So the script will search for device types based on the `model`, meaning if the device type library has updated the model numbers of these Ubiquiti devices, this script should not find an existing entry in the DB under the new model and go on creating it. It won't update the existing one.

Can you check if there are not new Ubiquiti device types in your Netbox?

See: https://github.com/minitriga/Netbox-Device-Type-Library-Import/blob/e8ac3e779c5b42a7a5832a58c8c1644dc6fe8cad/nb-dt-import.py#L268-L327

**Comment by danner26** [comment] 2023-03-03 16:35
Hello @typecookie, this is an expected behavior just as @ndom91 described.

As a heads up, the NetBox Community will be taking over this repository. Due to the fact that this issue has been around for a very long time and we have updated the requirements within this repository as well as the new codebase for NetBox and DeviceType-Library, I am going to close it. Should you encounter any further issues, please feel free to contact us. Thank you!

**Closed by danner26** 2023-03-03 16:35 UTC
